/* This file is automatically generated by Lemon from input grammar
** source file "native/qjson_parse.y".
*/
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifier prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 11 "native/qjson_parse.y"

#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include "qjson.h"
#include "qjson_parse_ctx.h"
#line 37 "native/qjson_parse.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef TK_OR
#define TK_OR                           1
#define TK_AND                          2
#define TK_NOT                          3
#define TK_EQ                           4
#define TK_IN                           5
#define TK_PLUS                         6
#define TK_MINUS                        7
#define TK_STAR                         8
#define TK_SLASH                        9
#define TK_CARET                       10
#define TK_NULL                        11
#define TK_TRUE                        12
#define TK_FALSE                       13
#define TK_NUMBER                      14
#define TK_NUMBER_N                    15
#define TK_NUMBER_M                    16
#define TK_NUMBER_L                    17
#define TK_STRING                      18
#define TK_BLOB                        19
#define TK_UNBOUND                     20
#define TK_IDENT                       21
#define TK_RBRACKET                    22
#define TK_LBRACKET                    23
#define TK_COMMA                       24
#define TK_RBRACE                      25
#define TK_LBRACE                      26
#define TK_COLON                       27
#define TK_WHERE                       28
#define TK_LPAREN                      29
#define TK_RPAREN                      30
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    ParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is ParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    ParseARG_SDECL     A static variable declaration for the %extra_argument
**    ParseARG_PDECL     A parameter declaration for the %extra_argument
**    ParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    ParseARG_STORE     Code to store %extra_argument into yypParser
**    ParseARG_FETCH     Code to extract %extra_argument from yypParser
**    ParseCTX_*         As ParseARG_ except for %extra_context
**    YYREALLOC          Name of the realloc() function to use
**    YYFREE             Name of the free() function to use
**    YYDYNSTACK         True if stack space should be extended on heap
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
**    YY_MIN_DSTRCTR     Minimum symbol value that has a destructor
**    YY_MAX_DSTRCTR     Maximum symbol value that has a destructor
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 45
#define YYACTIONTYPE unsigned char
#define ParseTOKENTYPE  qjson_token 
typedef union {
  int yyinit;
  ParseTOKENTYPE yy0;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define ParseARG_SDECL  qjson_parse_ctx *ctx ;
#define ParseARG_PDECL , qjson_parse_ctx *ctx 
#define ParseARG_PARAM ,ctx 
#define ParseARG_FETCH  qjson_parse_ctx *ctx =yypParser->ctx ;
#define ParseARG_STORE yypParser->ctx =ctx ;
#define YYREALLOC realloc
#define YYFREE free
#define YYDYNSTACK 0
#define ParseCTX_SDECL
#define ParseCTX_PDECL
#define ParseCTX_PARAM
#define ParseCTX_FETCH
#define ParseCTX_STORE
#define YYNSTATE             40
#define YYNRULE              45
#define YYNRULE_WITH_ACTION  29
#define YYNTOKEN             31
#define YY_MAX_SHIFT         39
#define YY_MIN_SHIFTREDUCE   71
#define YY_MAX_SHIFTREDUCE   115
#define YY_ERROR_ACTION      116
#define YY_ACCEPT_ACTION     117
#define YY_NO_ACTION         118
#define YY_MIN_REDUCE        119
#define YY_MAX_REDUCE        163
#define YY_MIN_DSTRCTR       0
#define YY_MAX_DSTRCTR       0
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif

/* Macro to determine if stack space has the ability to grow using
** heap memory.
*/
#if YYSTACKDEPTH<=0 || YYDYNSTACK
# define YYGROWABLESTACK 1
#else
# define YYGROWABLESTACK 0
#endif

/* Guarantee a minimum number of initial stack slots.
*/
#if YYSTACKDEPTH<=0
# undef YYSTACKDEPTH
# define YYSTACKDEPTH 2  /* Need a minimum stack size */
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (319)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */    38,   39,   20,    2,   20,   14,   20,  149,   20,    6,
 /*    10 */    17,   71,   72,   73,   74,   75,   76,   77,   78,   79,
 /*    20 */    80,   81,    8,   84,    4,   18,   87,   16,   83,    1,
 /*    30 */    71,   72,   73,   74,   75,   76,   77,   78,   79,   80,
 /*    40 */    81,    5,   84,   15,   85,   87,   71,   72,   73,   74,
 /*    50 */    75,   76,   77,   78,   79,   80,   81,   86,   84,  118,
 /*    60 */   118,   87,  118,  118,    7,   71,   72,   73,   74,   75,
 /*    70 */    76,   77,   78,   79,   80,   81,   82,   84,    3,    4,
 /*    80 */    87,   71,   72,   73,   74,   75,   76,   77,   78,   79,
 /*    90 */    80,   81,  118,   84,  118,  118,   87,   34,  118,   34,
 /*   100 */    14,  118,  118,   34,    6,  118,  118,   27,   27,   21,
 /*   110 */    34,  118,   34,   14,  118,  118,   34,    6,  118,  118,
 /*   120 */   140,  140,   22,   34,  118,   34,   14,  118,  118,   34,
 /*   130 */     6,  118,  118,   35,   35,   22,   34,  118,   34,   14,
 /*   140 */   148,  118,   34,    6,  118,  118,  138,  138,   22,   34,
 /*   150 */   118,   34,   14,  118,  118,   34,    6,  118,  118,   28,
 /*   160 */    28,   22,  117,   29,   30,   29,   14,  118,    5,   29,
 /*   170 */     6,   37,  118,   37,   14,  118,  118,   37,    6,   19,
 /*   180 */    19,  118,   13,  118,   12,   11,   10,    9,    8,   23,
 /*   190 */   118,   23,   14,  118,  118,   23,    6,   31,  118,   31,
 /*   200 */    14,   23,  118,   31,    6,   10,    9,    8,  115,   31,
 /*   210 */   118,   32,  118,   32,   14,  118,  118,   32,    6,   33,
 /*   220 */   118,   33,   14,   32,  118,   33,    6,    3,    4,  118,
 /*   230 */    25,   33,   25,   14,  118,  118,   25,    6,  118,  118,
 /*   240 */   118,   26,   25,   26,   14,  118,  118,   26,    6,  118,
 /*   250 */   118,  118,   24,   26,   24,   14,  113,  118,   24,    6,
 /*   260 */   118,  118,  118,  118,   24,   36,  157,   36,   14,  118,
 /*   270 */   118,   36,    6,  118,   37,  118,   37,   14,  118,  118,
 /*   280 */    37,    6,   13,  155,   12,   11,   10,    9,    8,   12,
 /*   290 */    11,   10,    9,    8,  118,  118,  118,  141,  118,  141,
 /*   300 */    14,  118,  118,  141,    6,  152,  118,  152,   14,  118,
 /*   310 */   118,  152,    6,  115,   12,   11,   10,    9,    8,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    37,   37,   32,    3,   34,   35,   36,    0,   38,   39,
 /*    10 */     5,   11,   12,   13,   14,   15,   16,   17,   18,   19,
 /*    20 */    20,   21,   10,   23,    2,   24,   26,   24,   22,   29,
 /*    30 */    11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
 /*    40 */    21,   28,   23,   27,   25,   26,   11,   12,   13,   14,
 /*    50 */    15,   16,   17,   18,   19,   20,   21,   25,   23,   45,
 /*    60 */    45,   26,   45,   45,   29,   11,   12,   13,   14,   15,
 /*    70 */    16,   17,   18,   19,   20,   21,   22,   23,    1,    2,
 /*    80 */    26,   11,   12,   13,   14,   15,   16,   17,   18,   19,
 /*    90 */    20,   21,   45,   23,   45,   45,   26,   32,   45,   34,
 /*   100 */    35,   45,   45,   38,   39,   45,   45,   42,   43,   44,
 /*   110 */    32,   45,   34,   35,   45,   45,   38,   39,   45,   45,
 /*   120 */    42,   43,   44,   32,   45,   34,   35,   45,   45,   38,
 /*   130 */    39,   45,   45,   42,   43,   44,   32,   45,   34,   35,
 /*   140 */     0,   45,   38,   39,   45,   45,   42,   43,   44,   32,
 /*   150 */    45,   34,   35,   45,   45,   38,   39,   45,   45,   42,
 /*   160 */    43,   44,   31,   32,   33,   34,   35,   45,   28,   38,
 /*   170 */    39,   32,   45,   34,   35,   45,   45,   38,   39,   40,
 /*   180 */    41,   45,    4,   45,    6,    7,    8,    9,   10,   32,
 /*   190 */    45,   34,   35,   45,   45,   38,   39,   32,   45,   34,
 /*   200 */    35,   44,   45,   38,   39,    8,    9,   10,   30,   44,
 /*   210 */    45,   32,   45,   34,   35,   45,   45,   38,   39,   32,
 /*   220 */    45,   34,   35,   44,   45,   38,   39,    1,    2,   45,
 /*   230 */    32,   44,   34,   35,   45,   45,   38,   39,   45,   45,
 /*   240 */    45,   32,   44,   34,   35,   45,   45,   38,   39,   45,
 /*   250 */    45,   45,   32,   44,   34,   35,   30,   45,   38,   39,
 /*   260 */    45,   45,   45,   45,   44,   32,   33,   34,   35,   45,
 /*   270 */    45,   38,   39,   45,   32,   45,   34,   35,   45,   45,
 /*   280 */    38,   39,    4,   41,    6,    7,    8,    9,   10,    6,
 /*   290 */     7,    8,    9,   10,   45,   45,   45,   32,   45,   34,
 /*   300 */    35,   45,   45,   38,   39,   32,   45,   34,   35,   45,
 /*   310 */    45,   38,   39,   30,    6,    7,    8,    9,   10,   45,
 /*   320 */    45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
 /*   330 */    45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
 /*   340 */    45,   45,   45,   45,   45,   45,   31,   31,   31,   31,
};
#define YY_SHIFT_COUNT    (39)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (308)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */    70,    0,    0,    0,    0,    0,   19,   35,   35,   35,
 /*    10 */    35,   35,   35,   35,   54,   70,   70,   70,   70,    3,
 /*    20 */     1,  178,  278,  283,  308,  197,  197,  226,   77,  140,
 /*    30 */     7,   12,   12,   12,    5,   22,   13,   16,   32,    6,
};
#define YY_REDUCE_COUNT (20)
#define YY_REDUCE_MIN   (-37)
#define YY_REDUCE_MAX   (273)
static const short yy_reduce_ofst[] = {
 /*     0 */   131,   65,   78,   91,  104,  117,  139,  157,  165,  179,
 /*    10 */   187,  198,  209,  220,  -30,  233,  242,  265,  273,  -37,
 /*    20 */   -36,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
 /*    10 */   116,  116,  116,  116,  116,  116,  159,  116,  159,  158,
 /*    20 */   158,  116,  116,  116,  142,  144,  143,  116,  137,  116,
 /*    30 */   116,  147,  146,  145,  162,  139,  156,  136,  116,  116,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  ParseARG_SDECL                /* A place to hold %extra_argument */
  ParseCTX_SDECL                /* A place to hold %extra_context */
  yyStackEntry *yystackEnd;           /* Last entry in the stack */
  yyStackEntry *yystack;              /* The parser stack */
  yyStackEntry yystk0[YYSTACKDEPTH];  /* Initial stack space */
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void ParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "TK_OR",
  /*    2 */ "TK_AND",
  /*    3 */ "TK_NOT",
  /*    4 */ "TK_EQ",
  /*    5 */ "TK_IN",
  /*    6 */ "TK_PLUS",
  /*    7 */ "TK_MINUS",
  /*    8 */ "TK_STAR",
  /*    9 */ "TK_SLASH",
  /*   10 */ "TK_CARET",
  /*   11 */ "TK_NULL",
  /*   12 */ "TK_TRUE",
  /*   13 */ "TK_FALSE",
  /*   14 */ "TK_NUMBER",
  /*   15 */ "TK_NUMBER_N",
  /*   16 */ "TK_NUMBER_M",
  /*   17 */ "TK_NUMBER_L",
  /*   18 */ "TK_STRING",
  /*   19 */ "TK_BLOB",
  /*   20 */ "TK_UNBOUND",
  /*   21 */ "TK_IDENT",
  /*   22 */ "TK_RBRACKET",
  /*   23 */ "TK_LBRACKET",
  /*   24 */ "TK_COMMA",
  /*   25 */ "TK_RBRACE",
  /*   26 */ "TK_LBRACE",
  /*   27 */ "TK_COLON",
  /*   28 */ "TK_WHERE",
  /*   29 */ "TK_LPAREN",
  /*   30 */ "TK_RPAREN",
  /*   31 */ "input",
  /*   32 */ "value",
  /*   33 */ "view_def",
  /*   34 */ "array",
  /*   35 */ "arr_open",
  /*   36 */ "elements",
  /*   37 */ "opt_comma",
  /*   38 */ "object",
  /*   39 */ "obj_open",
  /*   40 */ "entries",
  /*   41 */ "entry",
  /*   42 */ "condition",
  /*   43 */ "match_clause",
  /*   44 */ "expr",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "value ::= TK_NULL",
 /*   1 */ "value ::= TK_TRUE",
 /*   2 */ "value ::= TK_FALSE",
 /*   3 */ "value ::= TK_NUMBER",
 /*   4 */ "value ::= TK_NUMBER_N",
 /*   5 */ "value ::= TK_NUMBER_M",
 /*   6 */ "value ::= TK_NUMBER_L",
 /*   7 */ "value ::= TK_STRING",
 /*   8 */ "value ::= TK_BLOB",
 /*   9 */ "value ::= TK_UNBOUND",
 /*  10 */ "value ::= TK_IDENT",
 /*  11 */ "array ::= arr_open TK_RBRACKET",
 /*  12 */ "array ::= arr_open elements opt_comma TK_RBRACKET",
 /*  13 */ "arr_open ::= TK_LBRACKET",
 /*  14 */ "object ::= obj_open TK_RBRACE",
 /*  15 */ "object ::= obj_open entries opt_comma TK_RBRACE",
 /*  16 */ "obj_open ::= TK_LBRACE",
 /*  17 */ "entry ::= value",
 /*  18 */ "view_def ::= value TK_WHERE condition",
 /*  19 */ "condition ::= condition TK_AND condition",
 /*  20 */ "condition ::= condition TK_OR condition",
 /*  21 */ "condition ::= TK_NOT condition",
 /*  22 */ "match_clause ::= value TK_IN value",
 /*  23 */ "condition ::= expr TK_EQ expr",
 /*  24 */ "expr ::= expr TK_PLUS expr",
 /*  25 */ "expr ::= expr TK_MINUS expr",
 /*  26 */ "expr ::= expr TK_STAR expr",
 /*  27 */ "expr ::= expr TK_SLASH expr",
 /*  28 */ "expr ::= expr TK_CARET expr",
 /*  29 */ "input ::= value",
 /*  30 */ "input ::= view_def",
 /*  31 */ "value ::= array",
 /*  32 */ "elements ::= value",
 /*  33 */ "elements ::= elements TK_COMMA value",
 /*  34 */ "value ::= object",
 /*  35 */ "entries ::= entry",
 /*  36 */ "entries ::= entries TK_COMMA entry",
 /*  37 */ "entry ::= value TK_COLON value",
 /*  38 */ "entry ::= value TK_COLON view_def",
 /*  39 */ "opt_comma ::=",
 /*  40 */ "opt_comma ::= TK_COMMA",
 /*  41 */ "condition ::= match_clause",
 /*  42 */ "condition ::= TK_LPAREN condition TK_RPAREN",
 /*  43 */ "expr ::= value",
 /*  44 */ "expr ::= TK_LPAREN expr TK_RPAREN",
};
#endif /* NDEBUG */


#if YYGROWABLESTACK
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int oldSize = 1 + (int)(p->yystackEnd - p->yystack);
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = oldSize*2 + 100;
  idx = (int)(p->yytos - p->yystack);
  if( p->yystack==p->yystk0 ){
    pNew = YYREALLOC(0, newSize*sizeof(pNew[0]));
    if( pNew==0 ) return 1;
    memcpy(pNew, p->yystack, oldSize*sizeof(pNew[0]));
  }else{
    pNew = YYREALLOC(p->yystack, newSize*sizeof(pNew[0]));
    if( pNew==0 ) return 1;
  }
  p->yystack = pNew;
  p->yytos = &p->yystack[idx];
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
            yyTracePrompt, oldSize, newSize);
  }
#endif
  p->yystackEnd = &p->yystack[newSize-1];
  return 0;
}
#endif /* YYGROWABLESTACK */

#if !YYGROWABLESTACK
/* For builds that do no have a growable stack, yyGrowStack always
** returns an error.
*/
# define yyGrowStack(X) 1
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to ParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void ParseInit(void *yypRawParser ParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  ParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
  yypParser->yystack = yypParser->yystk0;
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to Parse and ParseFree.
*/
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) ParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    ParseCTX_STORE
    ParseInit(yypParser ParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* Parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  ParseARG_FETCH
  ParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void ParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;

  /* In-lined version of calling yy_pop_parser_stack() for each
  ** element left in the stack */
  yyStackEntry *yytos = pParser->yytos;
  while( yytos>pParser->yystack ){
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sPopping %s\n",
        yyTracePrompt,
        yyTokenName[yytos->major]);
    }
#endif
    if( yytos->major>=YY_MIN_DSTRCTR ){
      yy_destructor(pParser, yytos->major, &yytos->minor);
    }
    yytos--;
  }

#if YYGROWABLESTACK
  if( pParser->yystack!=pParser->yystk0 ) YYFREE(pParser->yystack);
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  ParseFinalize(p);
  (*freeProc)(p);
}
#endif /* Parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int ParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int ParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   ParseARG_FETCH
   ParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   ParseARG_STORE /* Suppress warning about unused %extra_argument var */
   ParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  ParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
  yytos = yypParser->yytos;
  if( yytos>yypParser->yystackEnd ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
    yytos = yypParser->yytos;
    assert( yytos <= yypParser->yystackEnd );
  }
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    32,  /* (0) value ::= TK_NULL */
    32,  /* (1) value ::= TK_TRUE */
    32,  /* (2) value ::= TK_FALSE */
    32,  /* (3) value ::= TK_NUMBER */
    32,  /* (4) value ::= TK_NUMBER_N */
    32,  /* (5) value ::= TK_NUMBER_M */
    32,  /* (6) value ::= TK_NUMBER_L */
    32,  /* (7) value ::= TK_STRING */
    32,  /* (8) value ::= TK_BLOB */
    32,  /* (9) value ::= TK_UNBOUND */
    32,  /* (10) value ::= TK_IDENT */
    34,  /* (11) array ::= arr_open TK_RBRACKET */
    34,  /* (12) array ::= arr_open elements opt_comma TK_RBRACKET */
    35,  /* (13) arr_open ::= TK_LBRACKET */
    38,  /* (14) object ::= obj_open TK_RBRACE */
    38,  /* (15) object ::= obj_open entries opt_comma TK_RBRACE */
    39,  /* (16) obj_open ::= TK_LBRACE */
    41,  /* (17) entry ::= value */
    33,  /* (18) view_def ::= value TK_WHERE condition */
    42,  /* (19) condition ::= condition TK_AND condition */
    42,  /* (20) condition ::= condition TK_OR condition */
    42,  /* (21) condition ::= TK_NOT condition */
    43,  /* (22) match_clause ::= value TK_IN value */
    42,  /* (23) condition ::= expr TK_EQ expr */
    44,  /* (24) expr ::= expr TK_PLUS expr */
    44,  /* (25) expr ::= expr TK_MINUS expr */
    44,  /* (26) expr ::= expr TK_STAR expr */
    44,  /* (27) expr ::= expr TK_SLASH expr */
    44,  /* (28) expr ::= expr TK_CARET expr */
    31,  /* (29) input ::= value */
    31,  /* (30) input ::= view_def */
    32,  /* (31) value ::= array */
    36,  /* (32) elements ::= value */
    36,  /* (33) elements ::= elements TK_COMMA value */
    32,  /* (34) value ::= object */
    40,  /* (35) entries ::= entry */
    40,  /* (36) entries ::= entries TK_COMMA entry */
    41,  /* (37) entry ::= value TK_COLON value */
    41,  /* (38) entry ::= value TK_COLON view_def */
    37,  /* (39) opt_comma ::= */
    37,  /* (40) opt_comma ::= TK_COMMA */
    42,  /* (41) condition ::= match_clause */
    42,  /* (42) condition ::= TK_LPAREN condition TK_RPAREN */
    44,  /* (43) expr ::= value */
    44,  /* (44) expr ::= TK_LPAREN expr TK_RPAREN */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) value ::= TK_NULL */
   -1,  /* (1) value ::= TK_TRUE */
   -1,  /* (2) value ::= TK_FALSE */
   -1,  /* (3) value ::= TK_NUMBER */
   -1,  /* (4) value ::= TK_NUMBER_N */
   -1,  /* (5) value ::= TK_NUMBER_M */
   -1,  /* (6) value ::= TK_NUMBER_L */
   -1,  /* (7) value ::= TK_STRING */
   -1,  /* (8) value ::= TK_BLOB */
   -1,  /* (9) value ::= TK_UNBOUND */
   -1,  /* (10) value ::= TK_IDENT */
   -2,  /* (11) array ::= arr_open TK_RBRACKET */
   -4,  /* (12) array ::= arr_open elements opt_comma TK_RBRACKET */
   -1,  /* (13) arr_open ::= TK_LBRACKET */
   -2,  /* (14) object ::= obj_open TK_RBRACE */
   -4,  /* (15) object ::= obj_open entries opt_comma TK_RBRACE */
   -1,  /* (16) obj_open ::= TK_LBRACE */
   -1,  /* (17) entry ::= value */
   -3,  /* (18) view_def ::= value TK_WHERE condition */
   -3,  /* (19) condition ::= condition TK_AND condition */
   -3,  /* (20) condition ::= condition TK_OR condition */
   -2,  /* (21) condition ::= TK_NOT condition */
   -3,  /* (22) match_clause ::= value TK_IN value */
   -3,  /* (23) condition ::= expr TK_EQ expr */
   -3,  /* (24) expr ::= expr TK_PLUS expr */
   -3,  /* (25) expr ::= expr TK_MINUS expr */
   -3,  /* (26) expr ::= expr TK_STAR expr */
   -3,  /* (27) expr ::= expr TK_SLASH expr */
   -3,  /* (28) expr ::= expr TK_CARET expr */
   -1,  /* (29) input ::= value */
   -1,  /* (30) input ::= view_def */
   -1,  /* (31) value ::= array */
   -1,  /* (32) elements ::= value */
   -3,  /* (33) elements ::= elements TK_COMMA value */
   -1,  /* (34) value ::= object */
   -1,  /* (35) entries ::= entry */
   -3,  /* (36) entries ::= entries TK_COMMA entry */
   -3,  /* (37) entry ::= value TK_COLON value */
   -3,  /* (38) entry ::= value TK_COLON view_def */
    0,  /* (39) opt_comma ::= */
   -1,  /* (40) opt_comma ::= TK_COMMA */
   -1,  /* (41) condition ::= match_clause */
   -3,  /* (42) condition ::= TK_LPAREN condition TK_RPAREN */
   -1,  /* (43) expr ::= value */
   -3,  /* (44) expr ::= TK_LPAREN expr TK_RPAREN */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  ParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  ParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  ParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
      case 0: /* value ::= TK_NULL */
#line 47 "native/qjson_parse.y"
{
    qjson_val *v = qjson_ctx_alloc_val(ctx, QJSON_NULL);
    qjson_ctx_push(ctx, v);
}
#line 1108 "native/qjson_parse.c"
        break;
      case 1: /* value ::= TK_TRUE */
#line 52 "native/qjson_parse.y"
{
    qjson_val *v = qjson_ctx_alloc_val(ctx, QJSON_TRUE);
    qjson_ctx_push(ctx, v);
}
#line 1116 "native/qjson_parse.c"
        break;
      case 2: /* value ::= TK_FALSE */
#line 57 "native/qjson_parse.y"
{
    qjson_val *v = qjson_ctx_alloc_val(ctx, QJSON_FALSE);
    qjson_ctx_push(ctx, v);
}
#line 1124 "native/qjson_parse.c"
        break;
      case 3: /* value ::= TK_NUMBER */
#line 62 "native/qjson_parse.y"
{
    qjson_val *v = qjson_ctx_alloc_val(ctx, QJSON_NUMBER);
    if (v) v->num = yymsp[0].minor.yy0.num;
    qjson_ctx_push(ctx, v);
}
#line 1133 "native/qjson_parse.c"
        break;
      case 4: /* value ::= TK_NUMBER_N */
#line 68 "native/qjson_parse.y"
{
    qjson_val *v = qjson_ctx_alloc_val(ctx, QJSON_BIGINT);
    if (v) { v->str.s = yymsp[0].minor.yy0.start; v->str.len = yymsp[0].minor.yy0.len; }
    qjson_ctx_push(ctx, v);
}
#line 1142 "native/qjson_parse.c"
        break;
      case 5: /* value ::= TK_NUMBER_M */
#line 74 "native/qjson_parse.y"
{
    qjson_val *v = qjson_ctx_alloc_val(ctx, QJSON_BIGDECIMAL);
    if (v) { v->str.s = yymsp[0].minor.yy0.start; v->str.len = yymsp[0].minor.yy0.len; }
    qjson_ctx_push(ctx, v);
}
#line 1151 "native/qjson_parse.c"
        break;
      case 6: /* value ::= TK_NUMBER_L */
#line 80 "native/qjson_parse.y"
{
    qjson_val *v = qjson_ctx_alloc_val(ctx, QJSON_BIGFLOAT);
    if (v) { v->str.s = yymsp[0].minor.yy0.start; v->str.len = yymsp[0].minor.yy0.len; }
    qjson_ctx_push(ctx, v);
}
#line 1160 "native/qjson_parse.c"
        break;
      case 7: /* value ::= TK_STRING */
      case 10: /* value ::= TK_IDENT */ yytestcase(yyruleno==10);
#line 86 "native/qjson_parse.y"
{
    qjson_val *v = qjson_ctx_alloc_val(ctx, QJSON_STRING);
    if (v) { v->str.s = yymsp[0].minor.yy0.decoded; v->str.len = yymsp[0].minor.yy0.decoded_len; }
    qjson_ctx_push(ctx, v);
}
#line 1170 "native/qjson_parse.c"
        break;
      case 8: /* value ::= TK_BLOB */
#line 92 "native/qjson_parse.y"
{
    qjson_val *v = qjson_ctx_alloc_val(ctx, QJSON_BLOB);
    if (v) { v->blob.data = yymsp[0].minor.yy0.decoded; v->blob.len = yymsp[0].minor.yy0.decoded_len; }
    qjson_ctx_push(ctx, v);
}
#line 1179 "native/qjson_parse.c"
        break;
      case 9: /* value ::= TK_UNBOUND */
#line 98 "native/qjson_parse.y"
{
    qjson_val *v = qjson_ctx_alloc_val(ctx, QJSON_UNBOUND);
    if (v) { v->str.s = yymsp[0].minor.yy0.decoded; v->str.len = yymsp[0].minor.yy0.decoded_len; }
    qjson_ctx_push(ctx, v);
}
#line 1188 "native/qjson_parse.c"
        break;
      case 11: /* array ::= arr_open TK_RBRACKET */
      case 12: /* array ::= arr_open elements opt_comma TK_RBRACKET */ yytestcase(yyruleno==12);
#line 114 "native/qjson_parse.y"
{
    qjson_ctx_push_array(ctx);
}
#line 1196 "native/qjson_parse.c"
        break;
      case 13: /* arr_open ::= TK_LBRACKET */
      case 16: /* obj_open ::= TK_LBRACE */ yytestcase(yyruleno==16);
#line 122 "native/qjson_parse.y"
{
    qjson_ctx_push_mark(ctx);
}
#line 1204 "native/qjson_parse.c"
        break;
      case 14: /* object ::= obj_open TK_RBRACE */
      case 15: /* object ::= obj_open entries opt_comma TK_RBRACE */ yytestcase(yyruleno==15);
#line 133 "native/qjson_parse.y"
{
    qjson_ctx_push_object(ctx);
}
#line 1212 "native/qjson_parse.c"
        break;
      case 17: /* entry ::= value */
#line 152 "native/qjson_parse.y"
{
    qjson_val *t = qjson_ctx_alloc_val(ctx, QJSON_TRUE);
    qjson_ctx_push(ctx, t);
}
#line 1220 "native/qjson_parse.c"
        break;
      case 18: /* view_def ::= value TK_WHERE condition */
#line 167 "native/qjson_parse.y"
{
    qjson_ctx_push_view(ctx);
}
#line 1227 "native/qjson_parse.c"
        break;
      case 19: /* condition ::= condition TK_AND condition */
#line 175 "native/qjson_parse.y"
{
    qjson_ctx_push_binop(ctx, "and", 3);
}
#line 1234 "native/qjson_parse.c"
        break;
      case 20: /* condition ::= condition TK_OR condition */
#line 179 "native/qjson_parse.y"
{
    qjson_ctx_push_binop(ctx, "or", 2);
}
#line 1241 "native/qjson_parse.c"
        break;
      case 21: /* condition ::= TK_NOT condition */
#line 183 "native/qjson_parse.y"
{
    qjson_ctx_push_notop(ctx);
}
#line 1248 "native/qjson_parse.c"
        break;
      case 22: /* match_clause ::= value TK_IN value */
#line 191 "native/qjson_parse.y"
{
    qjson_ctx_push_match(ctx);
}
#line 1255 "native/qjson_parse.c"
        break;
      case 23: /* condition ::= expr TK_EQ expr */
#line 197 "native/qjson_parse.y"
{
    qjson_ctx_push_equation(ctx);
}
#line 1262 "native/qjson_parse.c"
        break;
      case 24: /* expr ::= expr TK_PLUS expr */
#line 204 "native/qjson_parse.y"
{ qjson_ctx_push_arith(ctx, "+", 1); }
#line 1267 "native/qjson_parse.c"
        break;
      case 25: /* expr ::= expr TK_MINUS expr */
#line 205 "native/qjson_parse.y"
{ qjson_ctx_push_arith(ctx, "-", 1); }
#line 1272 "native/qjson_parse.c"
        break;
      case 26: /* expr ::= expr TK_STAR expr */
#line 206 "native/qjson_parse.y"
{ qjson_ctx_push_arith(ctx, "*", 1); }
#line 1277 "native/qjson_parse.c"
        break;
      case 27: /* expr ::= expr TK_SLASH expr */
#line 207 "native/qjson_parse.y"
{ qjson_ctx_push_arith(ctx, "/", 1); }
#line 1282 "native/qjson_parse.c"
        break;
      case 28: /* expr ::= expr TK_CARET expr */
#line 208 "native/qjson_parse.y"
{ qjson_ctx_push_arith(ctx, "^", 1); }
#line 1287 "native/qjson_parse.c"
        break;
      default:
      /* (29) input ::= value */ yytestcase(yyruleno==29);
      /* (30) input ::= view_def */ yytestcase(yyruleno==30);
      /* (31) value ::= array (OPTIMIZED OUT) */ assert(yyruleno!=31);
      /* (32) elements ::= value (OPTIMIZED OUT) */ assert(yyruleno!=32);
      /* (33) elements ::= elements TK_COMMA value */ yytestcase(yyruleno==33);
      /* (34) value ::= object (OPTIMIZED OUT) */ assert(yyruleno!=34);
      /* (35) entries ::= entry (OPTIMIZED OUT) */ assert(yyruleno!=35);
      /* (36) entries ::= entries TK_COMMA entry */ yytestcase(yyruleno==36);
      /* (37) entry ::= value TK_COLON value */ yytestcase(yyruleno==37);
      /* (38) entry ::= value TK_COLON view_def */ yytestcase(yyruleno==38);
      /* (39) opt_comma ::= */ yytestcase(yyruleno==39);
      /* (40) opt_comma ::= TK_COMMA */ yytestcase(yyruleno==40);
      /* (41) condition ::= match_clause (OPTIMIZED OUT) */ assert(yyruleno!=41);
      /* (42) condition ::= TK_LPAREN condition TK_RPAREN */ yytestcase(yyruleno==42);
      /* (43) expr ::= value */ yytestcase(yyruleno==43);
      /* (44) expr ::= TK_LPAREN expr TK_RPAREN */ yytestcase(yyruleno==44);
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 26 "native/qjson_parse.y"

    ctx->error = 1;
#line 1350 "native/qjson_parse.c"
/************ End %parse_failure code *****************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  ParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 22 "native/qjson_parse.y"

    ctx->error = 1;
#line 1372 "native/qjson_parse.c"
/************ End %syntax_error code ******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "ParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  ParseTOKENTYPE yyminor       /* The value for the token */
  ParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  ParseCTX_FETCH
  ParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
        if( yypParser->yytos>=yypParser->yystackEnd ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor ParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int ParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
