#define TK_OR                            1
#define TK_AND                           2
#define TK_NOT                           3
#define TK_EQ                            4
#define TK_IN                            5
#define TK_PLUS                          6
#define TK_MINUS                         7
#define TK_STAR                          8
#define TK_SLASH                         9
#define TK_CARET                        10
#define TK_NULL                         11
#define TK_TRUE                         12
#define TK_FALSE                        13
#define TK_NUMBER                       14
#define TK_NUMBER_N                     15
#define TK_NUMBER_M                     16
#define TK_NUMBER_L                     17
#define TK_STRING                       18
#define TK_BLOB                         19
#define TK_UNBOUND                      20
#define TK_IDENT                        21
#define TK_RBRACKET                     22
#define TK_LBRACKET                     23
#define TK_COMMA                        24
#define TK_RBRACE                       25
#define TK_LBRACE                       26
#define TK_COLON                        27
#define TK_WHERE                        28
#define TK_LPAREN                       29
#define TK_RPAREN                       30
