/* ============================================================
 * qjq.c — QJSON query tool
 *
 * QuickJS + QJSON + SQLite in one binary.
 *
 * Phase 1: parse/stringify (pipe mode)
 * Phase 2: SQLite + path queries + --eval
 * ============================================================ */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "quickjs.h"
#include "quickjs-libc.h"

/* Embedded qjson.js source (generated by Makefile) */
#include "qjson_js.h"

/* ── Read all of stdin ──────────────────────────────────────── */

static char *read_stdin(size_t *out_len) {
    size_t cap = 4096, len = 0;
    char *buf = malloc(cap);
    if (!buf) return NULL;
    for (;;) {
        size_t n = fread(buf + len, 1, cap - len, stdin);
        len += n;
        if (n == 0) break;
        if (len == cap) {
            cap *= 2;
            char *nb = realloc(buf, cap);
            if (!nb) { free(buf); return NULL; }
            buf = nb;
        }
    }
    buf[len] = '\0';
    *out_len = len;
    return buf;
}

/* ── Usage ──────────────────────────────────────────────────── */

static void usage(const char *prog) {
    fprintf(stderr,
        "Usage: %s [OPTIONS] [PATH]\n"
        "\n"
        "QJSON query tool — parse, format, query.\n"
        "\n"
        "Input:\n"
        "  stdin               QJSON text (default)\n"
        "  -e EXPR             evaluate JS expression\n"
        "\n"
        "Output:\n"
        "  -i N                indent (pretty-print)\n"
        "  -r                  raw output (no quotes on strings)\n"
        "  -c                  compact (default)\n"
        "\n"
        "Examples:\n"
        "  echo '{a: 1, b: 2}' | %s\n"
        "  echo '42N' | %s\n"
        "  %s -e 'qjson_parse(\"[1,2,3]\")'\n"
        , prog, prog, prog, prog);
}

/* ── Main ───────────────────────────────────────────────────── */

int main(int argc, char **argv) {
    const char *eval_expr = NULL;
    int indent = -1;  /* -1 = compact */
    int raw = 0;
    int i;

    /* Parse args */
    for (i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0) {
            usage(argv[0]);
            return 0;
        } else if (strcmp(argv[i], "-e") == 0 && i + 1 < argc) {
            eval_expr = argv[++i];
        } else if (strcmp(argv[i], "-i") == 0 && i + 1 < argc) {
            indent = atoi(argv[++i]);
        } else if (strcmp(argv[i], "-r") == 0) {
            raw = 1;
        } else if (strcmp(argv[i], "-c") == 0) {
            indent = -1;
        } else {
            fprintf(stderr, "qjq: unknown option: %s\n", argv[i]);
            usage(argv[0]);
            return 1;
        }
    }

    /* Init QuickJS */
    JSRuntime *rt = JS_NewRuntime();
    if (!rt) { fprintf(stderr, "qjq: failed to create JS runtime\n"); return 1; }
    JSContext *ctx = JS_NewContext(rt);
    if (!ctx) { fprintf(stderr, "qjq: failed to create JS context\n"); return 1; }

    /* Add std/os modules for console, etc. */
    js_std_add_helpers(ctx, argc, argv);

    /* Load qjson.js — eval as script (functions become global) */
    JSValue ret = JS_Eval(ctx, qjson_js_source, qjson_js_source_len,
                          "qjson.js", JS_EVAL_TYPE_GLOBAL);
    if (JS_IsException(ret)) {
        JSValue exc = JS_GetException(ctx);
        const char *str = JS_ToCString(ctx, exc);
        fprintf(stderr, "qjq: failed to load qjson.js: %s\n", str ? str : "(null)");
        JS_FreeCString(ctx, str);
        JS_FreeValue(ctx, exc);
        JS_FreeValue(ctx, ret);
        return 1;
    }
    JS_FreeValue(ctx, ret);

    /* Execute */
    const char *result_str = NULL;
    JSValue result;

    if (eval_expr) {
        /* -e: evaluate arbitrary JS expression */
        result = JS_Eval(ctx, eval_expr, strlen(eval_expr),
                         "<eval>", JS_EVAL_TYPE_GLOBAL);
    } else {
        /* Pipe mode: read stdin, parse, stringify */
        size_t input_len;
        char *input = read_stdin(&input_len);
        if (!input) { fprintf(stderr, "qjq: failed to read stdin\n"); return 1; }

        /* Build: qjson_stringify(qjson_parse(input), null, indent) */
        char *js_code;
        size_t js_len;
        if (indent >= 0) {
            /* Pretty-print with indent */
            const char *fmt = "qjson_stringify(qjson_parse(%s), null, %d)";
            /* Escape input as a JS string */
            js_len = strlen(fmt) + input_len * 2 + 32;
            js_code = malloc(js_len);
            /* Use JSON.stringify to safely quote the input string */
            JSValue input_val = JS_NewStringLen(ctx, input, input_len);
            JSValue json_str = JS_JSONStringify(ctx, input_val, JS_UNDEFINED, JS_UNDEFINED);
            const char *quoted = JS_ToCString(ctx, json_str);
            snprintf(js_code, js_len, fmt, quoted, indent);
            JS_FreeCString(ctx, quoted);
            JS_FreeValue(ctx, json_str);
            JS_FreeValue(ctx, input_val);
        } else {
            /* Compact */
            const char *fmt = "qjson_stringify(qjson_parse(%s))";
            JSValue input_val = JS_NewStringLen(ctx, input, input_len);
            JSValue json_str = JS_JSONStringify(ctx, input_val, JS_UNDEFINED, JS_UNDEFINED);
            const char *quoted = JS_ToCString(ctx, json_str);
            js_len = strlen(fmt) + strlen(quoted) + 32;
            js_code = malloc(js_len);
            snprintf(js_code, js_len, fmt, quoted);
            JS_FreeCString(ctx, quoted);
            JS_FreeValue(ctx, json_str);
            JS_FreeValue(ctx, input_val);
        }
        free(input);

        result = JS_Eval(ctx, js_code, strlen(js_code),
                         "<pipe>", JS_EVAL_TYPE_GLOBAL);
        free(js_code);
    }

    /* Output */
    if (JS_IsException(result)) {
        JSValue exc = JS_GetException(ctx);
        const char *str = JS_ToCString(ctx, exc);
        fprintf(stderr, "qjq: %s\n", str ? str : "error");
        JS_FreeCString(ctx, str);
        JS_FreeValue(ctx, exc);
        JS_FreeValue(ctx, result);
        JS_FreeContext(ctx);
        JS_FreeRuntime(rt);
        return 1;
    }

    if (!JS_IsUndefined(result)) {
        result_str = JS_ToCString(ctx, result);
        if (result_str) {
            if (raw && result_str[0] == '"') {
                /* Strip surrounding quotes for -r */
                size_t len = strlen(result_str);
                if (len >= 2 && result_str[len-1] == '"')
                    fwrite(result_str + 1, 1, len - 2, stdout);
                else
                    fputs(result_str, stdout);
            } else {
                fputs(result_str, stdout);
            }
            fputc('\n', stdout);
            JS_FreeCString(ctx, result_str);
        }
    }

    JS_FreeValue(ctx, result);
    JS_FreeContext(ctx);
    JS_FreeRuntime(rt);
    return 0;
}
